ESX = nil

PlayerData = {}

TriggerEvent('LandLife:GetSharedObject', function(obj) ESX = obj PlayerData = ESX.GetPlayerData() end)

local currentTattoos = {}
local nearByPlayer = nil

RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
	PlayerData.job = job
end)

local inAction = false

AddEventHandler('skinchanger:modelLoaded', function()
	ESX.TriggerServerCallback('tattoo:getTattoos', function(tattooList)
		if tattooList then
			for k,v in pairs(tattooList) do
				ApplyPedOverlay(PlayerPedId(), v.collection, v.texture)
			end
			currentTattoos = tattooList
		end
	end)
end)
 
RegisterNetEvent("esx:playerLoaded")
AddEventHandler("esx:playerLoaded", function(xPlayer)
    PlayerData = xPlayer
end)

-- RegisterCommand("rtatouage", function()
--     refreshAllTattoo()
-- end, false)

function refreshAllTattoo()
	currentTattoos = {}
	ClearPedDecorations(PlayerPedId())
	ESX.TriggerServerCallback('tattoo:getTattoos', function(tattooList)
		if tattooList then
			for k,v in pairs(tattooList) do
				ApplyPedOverlay(PlayerPedId(), v.collection, v.texture)
			end
			currentTattoos = tattooList
		end
	end)
end

Tatoos = {
    CatSelected = nil,
    Iterator = nil,
	price = 0
}
Tatoos.MenuOpened = false
Tatoos.MainMenu = RageUI.CreateMenu("", "Catégories", nil, 100, "shopui_title_tattoos2", "shopui_title_tattoos2")
Tatoos.SubMenu = RageUI.CreateSubMenu(Tatoos.MainMenu, "", "Tatouages disponibles", nil, 100, "shopui_title_tattoos2", "shopui_title_tattoos2")
Tatoos.Achat = RageUI.CreateSubMenu(Tatoos.SubMenu, "", "Confirmation", nil, 100, "shopui_title_tattoos2", "shopui_title_tattoos2")
Tatoos.MainMenu.Closed = function()
    RageUI.Visible(Tatoos.MainMenu, false)
    Tatoos.MenuOpened = false
	TriggerServerEvent("CloseMenu", nearByPlayer)
end

RegisterNetEvent("CloseMenu")
AddEventHandler("CloseMenu", function()
	ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
        TriggerEvent('skinchanger:loadSkin', skin)
    end)
	-- ESX.Notification("Merci d'être passé ! A bientôt")
	refreshAllTattoo()
end)

local Categorie = 0

function OpenTattosMenu()
    if Tatoos.MenuOpened then
        Tatoos.MenuOpened = false
        RageUI.Visible(Tatoos.MainMenu, false)
    else
        Tatoos.MenuOpened = true
		Tatoos.CatSelected = nil
		Tatoos.Iterator = nil
        RageUI.Visible(Tatoos.MainMenu, true)
		TriggerServerEvent('OpenMenu', nearByPlayer)
        CreateThread(function()
            while Tatoos.MenuOpened do
                RageUI.IsVisible(Tatoos.MainMenu, function()
					RageUI.Button("Torse", nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 0
                        end
                    }, Tatoos.SubMenu)
                    RageUI.Button("Tête", nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 1
                        end
                    }, Tatoos.SubMenu)
                    RageUI.Button("Bras gauche", nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 2
                        end
                    }, Tatoos.SubMenu)
                    RageUI.Button("Bras droit", nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 3
                        end
                    }, Tatoos.SubMenu)
                    RageUI.Button("Jambe gauche", nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 4
                        end
                    }, Tatoos.SubMenu)
                    RageUI.Button("Jambe droite",  nil, {RightLabel = nil}, true, {
                        onSelected = function()
                            Categorie = 5
                        end
                    }, Tatoos.SubMenu)
					RageUI.Button("~r~Enlever tous les tattoos de la personne",  nil, {RightLabel = "→"}, true, {
                        onSelected = function()
                            TriggerServerEvent("DeleteTatoos", nearByPlayer)
                        end
                    })
                      
                end)
                RageUI.IsVisible(Tatoos.SubMenu, function()
                    for k,v in pairs(Tatouage.Liste) do
                        if GetPedDecorationZoneFromHashes(v[1], v[2]) == Categorie then
                            RageUI.Button("Tatouage "..k, nil, {RightLabel = "→"}, true, {
                                onActive = function()
									Tatoos.CatSelected = v[1]
									Tatoos.Iterator = v[2]
									if LastTatoos ~= Tatoos.Iterator then
										TriggerServerEvent("SVDrawTattoo", nearByPlayer, Tatoos.CatSelected, Tatoos.Iterator)
										LastTatoos = Tatoos.Iterator
									end
                                end
                            }, Tatoos.Achat)
                        end
                    end
                end)
				RageUI.IsVisible(Tatoos.Achat, function()
					RageUI.Button("Dessiner le tatoo", nil, {RightLabel = "→"}, not InAction, {
						onSelected = function()
                            InAction = true
							Tatoos.Achat.Closable = false
							RequestAnimDict('anim@amb@clubhouse@tutorial@bkr_tut_ig3@')
							while not HasAnimDictLoaded('anim@amb@clubhouse@tutorial@bkr_tut_ig3@') do
							Citizen.Wait(0)
							end
							local x,y,z = table.unpack(GetEntityCoords(PlayerPedId()))
							local prop_name = "v_ilev_ta_tatgun"
							Jointsupp = CreateObject(GetHashKey(prop_name), x, y, z,  true,  true, true)
							AttachEntityToEntity(Jointsupp, PlayerPedId(), GetPedBoneIndex(PlayerPedId(), 28422), -0.0, 0.03, 0, 0, -270.0, -20.0, true, true, false, true, 1, true)
							TaskPlayAnim(PlayerPedId(), "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", "machinic_loop_mechandplayer", 8.00, -8.00, -1, (2 + 16 + 32), 0.00, 0, 0, 0)
							Wait(7000)
							DeleteObject(Jointsupp)
							DetachEntity(Jointsupp, 1, true)
							ClearPedTasksImmediately(PlayerPedId())
							TriggerServerEvent("Validate", nearByPlayer, Tatoos.CatSelected, Tatoos.Iterator)
							Tatoos.Achat.Closable = true
                            InAction = false
						end
					})
				end)
                Wait(1)
            end
        end)
    end
end

RegisterNetEvent("ReceiveValidate")
AddEventHandler("ReceiveValidate", function(CatSelected, Iterator, Id)
	table.insert(currentTattoos, {collection = CatSelected, texture = Iterator})
	TriggerServerEvent("PutTatooInBase", currentTattoos, Id)
end)

RegisterNetEvent("DeleteTatoos")
AddEventHandler("DeleteTatoos", function(Id)
    currentTattoos = {}
    TriggerServerEvent("PutTatooInBase", currentTattoos, Id)
    Wait(1000)
    refreshAllTattoo()
end)

RegisterNetEvent("DrawTattoo")
AddEventHandler("DrawTattoo", function(CatSelected, Iterator)
    ClearPedDecorations(PlayerPedId())
    for k,v in pairs(currentTattoos) do
		ApplyPedOverlay(PlayerPedId(), v.collection, v.texture)
	end
    ApplyPedOverlay(PlayerPedId(), CatSelected, Iterator)
end)

RegisterNetEvent("OpenMenu")
AddEventHandler("OpenMenu", function()
    TriggerEvent('skinchanger:getSkin', function(skin)
        if skin.sex == 0 then
            TriggerEvent('skinchanger:loadSkin', {
                sex      = 0,
                tshirt_1 = 15,
                tshirt_2 = 0,
                arms     = 15,
                torso_1  = 15,
                torso_2  = 0,
                pants_1  = 14,
                pants_2  = 0,
                shoes_1  = 34,
                shoes_2  = 0,
                helmet_1  = -1,
                helmet_2  = 0,
                glasses_1  = -1,
                glasses_2  = 0,
                chain_1 = 0,
                chain_2 = 0,
                bags_1 = 0,
                bags_2 = 0
            })
        elseif skin.sex == 1 then
            TriggerEvent('skinchanger:loadSkin', {
                sex      = 1,
                tshirt_1 = 15,
                tshirt_2 = 0,
                arms     = 15,
                torso_1  = 15,
                torso_2  = 0,
                pants_1  = 15,
                pants_2  = 0,
                shoes_1  = 34,
                shoes_2  = 0,
                helmet_1  = -1,
                helmet_2  = 0,
                glasses_1  = -1,
                glasses_2  = 0,
                chain_1 = 0,
                chain_2 = 0,
                bags_1 = 0,
                bags_2 = 0
            })
        elseif skin.sex >= 2 then
        end
    end)
    refreshAllTattoo()
end)

local Tattoo = {
    {pos = vector3(1322.92, -1652.12, 51.29), job = "tattoo"},
    {pos = vector3(-1153.97, -1425.57, 3.96), job = "tattoo2"},
    {pos = vector3(322.02, 180.58, 102.60), job = "tattoo2"},
    {pos = vector3(1863.96, 3747.84, 32.04), job = "tattoo2"}
}

Citizen.CreateThread(function()
	while true do
		local Time = 1000
		for k, v in pairs(Tattoo) do
			local pos = GetEntityCoords(PlayerPedId())
			local dest = v.pos
			local distance = GetDistanceBetweenCoords(pos, dest, true)
			if distance < 1.5 and PlayerData.job.name == v.job then
				DisplayNotification("Appuyer ~INPUT_TALK~ pour ~b~accédez au salon de tatouages.")
				if IsControlJustPressed(1, 51) then
					local closestPlayer, closesPlayerDistance = ESX.Game.GetClosestPlayer()
                    if closesPlayerDistance ~= -1 and closesPlayerDistance <= 3.0 then
						nearByPlayer = GetPlayerServerId(closestPlayer)
                        OpenTattosMenu()
                    else
                        ESX.Notification("~r~Il n'y a personne à coté de vous")
                    end
				end
			end

            if distance < 5.5 and PlayerData.job.name == v.job then
                Time = 1
                DrawMarker(25, v.pos, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.8, 0.8, 93, 173, 226, 178, false, false, false, false)
            end
		end
		Citizen.Wait(Time)
	end
end)

Tatouage = {
    Liste = {
        {"mpairraces_overlays", "MP_Airraces_Tattoo_000_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_000_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_001_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_001_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_002_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_002_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_003_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_003_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_004_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_004_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_005_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_005_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_006_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_006_F"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_007_M"},
        {"mpairraces_overlays", "MP_Airraces_Tattoo_007_F"},
        {"mpbeach_overlays", "MP_Bea_F_Back_000"},
        {"mpbeach_overlays", "MP_Bea_F_Back_001"},
        {"mpbeach_overlays", "MP_Bea_F_Back_002"},
        {"mpbeach_overlays", "MP_Bea_F_Chest_000"},
        {"mpbeach_overlays", "MP_Bea_F_Chest_001"},
        {"mpbeach_overlays", "MP_Bea_F_Chest_002"},
        {"mpbeach_overlays", "MP_Bea_F_RSide_000"},
        {"mpbeach_overlays", "MP_Bea_F_RLeg_000"},
        {"mpbeach_overlays", "MP_Bea_F_RArm_001"},
        {"mpbeach_overlays", "MP_Bea_F_Neck_000"},
        {"mpbeach_overlays", "MP_Bea_F_Should_000"},
        {"mpbeach_overlays", "MP_Bea_F_Should_001"},
        {"mpbeach_overlays", "MP_Bea_F_Stom_000"},
        {"mpbeach_overlays", "MP_Bea_F_Stom_001"},
        {"mpbeach_overlays", "MP_Bea_F_Stom_002"},
        {"mpbeach_overlays", "MP_Bea_F_LArm_000"},
        {"mpbeach_overlays", "MP_Bea_F_LArm_001"},
        {"mpbeach_overlays", "MP_Bea_M_Back_000"},
        {"mpbeach_overlays", "MP_Bea_M_Chest_000"},
        {"mpbeach_overlays", "MP_Bea_M_Chest_001"},
        {"mpbeach_overlays", "MP_Bea_M_Head_000"},
        {"mpbeach_overlays", "MP_Bea_M_Head_001"},
        {"mpbeach_overlays", "MP_Bea_M_Head_002"},
        {"mpbeach_overlays", "MP_Bea_M_Lleg_000"},
        {"mpbeach_overlays", "MP_Bea_M_Rleg_000"},
        {"mpbeach_overlays", "MP_Bea_M_RArm_000"},
        {"mpbeach_overlays", "MP_Bea_M_LArm_000"},
        {"mpbeach_overlays", "MP_Bea_M_LArm_001"},
        {"mpbeach_overlays", "MP_Bea_M_Neck_000"},
        {"mpbeach_overlays", "MP_Bea_M_Neck_001"},
        {"mpbeach_overlays", "MP_Bea_M_RArm_001"},
        {"mpbeach_overlays", "MP_Bea_M_Stom_000"},
        {"mpbeach_overlays", "MP_Bea_M_Stom_001"},
        {"mpbeach_overlays", "FM_Hair_Fuzz"},
        {"mpbiker_overlays", "MP_Biker_Hair_000_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_000_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_001_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_001_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_002_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_002_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_003_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_003_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_004_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_004_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_005_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_005_F"},
        {"mpbiker_overlays", "MP_Biker_Hair_006_M"},
        {"mpbiker_overlays", "MP_Biker_Hair_006_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_000_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_000_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_001_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_001_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_002_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_002_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_003_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_003_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_004_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_004_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_005_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_005_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_006_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_006_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_007_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_007_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_008_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_008_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_009_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_009_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_010_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_010_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_011_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_011_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_012_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_012_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_013_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_013_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_014_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_014_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_015_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_015_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_016_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_016_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_017_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_017_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_018_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_018_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_019_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_019_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_020_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_020_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_021_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_021_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_022_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_022_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_023_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_023_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_024_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_024_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_025_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_025_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_026_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_026_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_027_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_027_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_028_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_028_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_029_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_029_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_030_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_030_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_031_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_031_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_032_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_032_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_033_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_033_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_034_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_034_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_035_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_035_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_036_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_036_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_037_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_037_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_038_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_038_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_039_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_039_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_040_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_040_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_041_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_041_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_042_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_042_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_043_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_043_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_044_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_044_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_045_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_045_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_046_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_046_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_047_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_047_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_048_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_048_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_049_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_049_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_050_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_050_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_051_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_051_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_052_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_052_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_053_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_053_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_054_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_054_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_055_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_055_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_056_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_056_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_057_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_057_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_058_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_058_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_059_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_059_F"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_060_M"},
        {"mpbiker_overlays", "MP_MP_Biker_Tat_060_F"},
        {"mpbusiness_overlays", "MP_Buis_M_Neck_000"},
        {"mpbusiness_overlays", "MP_Buis_M_Neck_001"},
        {"mpbusiness_overlays", "MP_Buis_M_Neck_002"},
        {"mpbusiness_overlays", "MP_Buis_M_Neck_003"},
        {"mpbusiness_overlays", "MP_Buis_M_LeftArm_000"},
        {"mpbusiness_overlays", "MP_Buis_M_LeftArm_001"},
        {"mpbusiness_overlays", "MP_Buis_M_RightArm_000"},
        {"mpbusiness_overlays", "MP_Buis_M_RightArm_001"},
        {"mpbusiness_overlays", "MP_Buis_M_Stomach_000"},
        {"mpbusiness_overlays", "MP_Buis_M_Chest_000"},
        {"mpbusiness_overlays", "MP_Buis_M_Chest_001"},
        {"mpbusiness_overlays", "MP_Buis_M_Back_000"},
        {"mpbusiness_overlays", "MP_Buis_F_Chest_000"},
        {"mpbusiness_overlays", "MP_Buis_F_Chest_001"},
        {"mpbusiness_overlays", "MP_Buis_F_Chest_002"},
        {"mpbusiness_overlays", "MP_Buis_F_Stom_000"},
        {"mpbusiness_overlays", "MP_Buis_F_Stom_001"},
        {"mpbusiness_overlays", "MP_Buis_F_Stom_002"},
        {"mpbusiness_overlays", "MP_Buis_F_Back_000"},
        {"mpbusiness_overlays", "MP_Buis_F_Back_001"},
        {"mpbusiness_overlays", "MP_Buis_F_Neck_000"},
        {"mpbusiness_overlays", "MP_Buis_F_Neck_001"},
        {"mpbusiness_overlays", "MP_Buis_F_RArm_000"},
        {"mpbusiness_overlays", "MP_Buis_F_LArm_000"},
        {"mpbusiness_overlays", "MP_Buis_F_LLeg_000"},
        {"mpbusiness_overlays", "MP_Buis_F_RLeg_000"},
        {"mpbusiness_overlays", "MP_Male_Crew_Tat_000"},
        {"mpbusiness_overlays", "MP_Male_Crew_Tat_001"},
        {"mpbusiness_overlays", "MP_Female_Crew_Tat_000"},
        {"mpbusiness_overlays", "MP_Female_Crew_Tat_001"},
        {"mpbusiness_overlays", "FM_Bus_F_Hair_a"},
        {"mpbusiness_overlays", "FM_Bus_F_Hair_b"},
        {"mpbusiness_overlays", "FM_Bus_F_Hair_c"},
        {"mpbusiness_overlays", "FM_Bus_F_Hair_d"},
        {"mpbusiness_overlays", "FM_Bus_F_Hair_e"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_000_a"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_000_b"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_000_c"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_000_d"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_000_e"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_001_a"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_001_b"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_001_c"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_001_d"},
        {"mpbusiness_overlays", "FM_Bus_M_Hair_001_e"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_000_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_000_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_001_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_001_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_002_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_002_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_003_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_003_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_004_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_004_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_005_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_005_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_006_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_006_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_007_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_007_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_008_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_008_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_009_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_009_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_010_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_010_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_011_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_011_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_012_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_012_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_013_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_013_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_014_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_014_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_015_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_015_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_016_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_016_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_017_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_017_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_018_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_018_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_019_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_019_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_020_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_020_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_021_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_021_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_022_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_022_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_023_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_023_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_024_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_024_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_025_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_025_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_026_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_026_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_027_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_027_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_028_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_028_F"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_029_M"},
        {"mpchristmas2017_overlays", "MP_Christmas2017_Tattoo_029_F"},
        {"mpchristmas2018_overlays", "MP_Christmas2018_Tat_000_M"},
        {"mpchristmas2018_overlays", "MP_Christmas2018_Tat_000_F"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_000"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_001"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_002"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_003"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_004"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_005"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_006"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_007"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_008"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_009"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_010"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_011"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_012"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_013"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_014"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_015"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_016"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_017"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_018"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_019"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_020"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_021"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_022"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_023"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_024"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_025"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_026"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_027"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_028"},
        {"mpchristmas2_overlays", "MP_Xmas2_M_Tat_029"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_000"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_001"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_002"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_003"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_004"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_005"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_006"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_007"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_008"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_009"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_010"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_011"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_012"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_013"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_014"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_015"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_016"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_017"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_018"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_019"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_020"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_021"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_022"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_023"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_024"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_025"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_026"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_027"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_028"},
        {"mpchristmas2_overlays", "MP_Xmas2_F_Tat_029"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Hair_M_000_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Hair_M_001_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Hair_F_000_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Hair_F_001_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_000_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_000_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_001_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_001_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_002_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_002_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_003_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_003_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_004_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_004_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_005_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_005_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_006_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_006_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_007_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_007_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_008_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_008_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_009_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_009_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_010_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_010_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_011_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_011_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_012_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_012_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_013_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_013_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_014_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_014_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_015_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_015_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_016_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_016_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_017_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_017_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_018_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_018_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_019_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_019_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_020_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_020_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_021_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_021_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_022_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_022_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_023_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_023_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_024_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_024_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_025_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_025_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_026_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_026_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_027_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_027_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_028_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_028_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_029_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_029_F"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_030_M"},
        {"mpgunrunning_overlays", "MP_Gunrunning_Tattoo_030_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_000_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_000_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_001_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_001_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_002_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_002_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_003_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_003_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_004_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_004_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_005_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_005_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_006_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_006_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_007_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_007_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_008_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_008_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_009_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_009_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_010_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_010_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_011_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_011_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_012_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_012_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_013_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_013_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_014_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_014_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_015_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_015_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_016_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_016_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_017_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_017_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_018_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_018_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_019_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_019_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_020_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_020_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_021_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_021_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_022_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_022_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_023_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_023_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_024_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_024_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_025_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_025_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_026_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_026_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_027_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_027_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_028_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_028_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_029_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_029_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_030_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_030_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_031_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_031_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_032_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_032_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_033_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_033_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_034_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_034_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_035_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_035_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_036_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_036_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_037_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_037_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_038_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_038_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_039_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_039_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_040_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_040_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_041_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_041_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_042_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_042_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_043_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_043_F"},
        {"mpheist3_overlays", "mpHeist3_Tat_044_M"},
        {"mpheist3_overlays", "mpHeist3_Tat_044_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_000_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_000_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_001_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_001_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_002_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_002_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_003_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_003_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_004_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_004_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_005_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_005_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_006_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_006_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_007_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_007_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_008_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_008_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_009_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_009_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_010_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_010_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_011_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_011_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_012_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_012_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_013_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_013_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_014_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_014_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_015_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_015_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_016_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_016_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_017_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_017_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_018_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_018_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_019_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_019_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_020_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_020_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_021_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_021_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_022_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_022_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_023_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_023_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_024_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_024_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_025_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_025_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_026_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_026_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_027_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_027_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_028_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_028_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_029_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_029_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_030_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_030_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_031_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_031_F"},
        {"mpheist4_overlays", "MP_Heist4_Tat_032_M"},
        {"mpheist4_overlays", "MP_Heist4_Tat_032_F"},
        {"mphipster_overlays", "FM_Hip_M_Hair_000_a"},
        {"mphipster_overlays", "FM_Hip_M_Hair_000_b"},
        {"mphipster_overlays", "FM_Hip_M_Hair_000_c"},
        {"mphipster_overlays", "FM_Hip_M_Hair_000_d"},
        {"mphipster_overlays", "FM_Hip_M_Hair_000_e"},
        {"mphipster_overlays", "FM_Hip_M_Hair_001_a"},
        {"mphipster_overlays", "FM_Hip_M_Hair_001_b"},
        {"mphipster_overlays", "FM_Hip_M_Hair_001_c"},
        {"mphipster_overlays", "FM_Hip_M_Hair_001_d"},
        {"mphipster_overlays", "FM_Hip_M_Hair_001_e"},
        {"mphipster_overlays", "FM_Hip_F_Hair_000_a"},
        {"mphipster_overlays", "FM_Hip_F_Hair_000_b"},
        {"mphipster_overlays", "FM_Hip_F_Hair_000_c"},
        {"mphipster_overlays", "FM_Hip_F_Hair_000_d"},
        {"mphipster_overlays", "FM_Hip_F_Hair_000_e"},
        {"mphipster_overlays", "FM_Hip_M_Tat_000"},
        {"mphipster_overlays", "FM_Hip_M_Tat_001"},
        {"mphipster_overlays", "FM_Hip_M_Tat_002"},
        {"mphipster_overlays", "FM_Hip_M_Tat_003"},
        {"mphipster_overlays", "FM_Hip_M_Tat_004"},
        {"mphipster_overlays", "FM_Hip_M_Tat_005"},
        {"mphipster_overlays", "FM_Hip_M_Tat_006"},
        {"mphipster_overlays", "FM_Hip_M_Tat_007"},
        {"mphipster_overlays", "FM_Hip_M_Tat_008"},
        {"mphipster_overlays", "FM_Hip_M_Tat_009"},
        {"mphipster_overlays", "FM_Hip_M_Tat_010"},
        {"mphipster_overlays", "FM_Hip_M_Tat_011"},
        {"mphipster_overlays", "FM_Hip_M_Tat_012"},
        {"mphipster_overlays", "FM_Hip_M_Tat_013"},
        {"mphipster_overlays", "FM_Hip_M_Tat_014"},
        {"mphipster_overlays", "FM_Hip_M_Tat_015"},
        {"mphipster_overlays", "FM_Hip_M_Tat_016"},
        {"mphipster_overlays", "FM_Hip_M_Tat_017"},
        {"mphipster_overlays", "FM_Hip_M_Tat_018"},
        {"mphipster_overlays", "FM_Hip_M_Tat_019"},
        {"mphipster_overlays", "FM_Hip_M_Tat_020"},
        {"mphipster_overlays", "FM_Hip_M_Tat_021"},
        {"mphipster_overlays", "FM_Hip_M_Tat_022"},
        {"mphipster_overlays", "FM_Hip_M_Tat_023"},
        {"mphipster_overlays", "FM_Hip_M_Tat_024"},
        {"mphipster_overlays", "FM_Hip_M_Tat_025"},
        {"mphipster_overlays", "FM_Hip_M_Tat_026"},
        {"mphipster_overlays", "FM_Hip_M_Tat_027"},
        {"mphipster_overlays", "FM_Hip_M_Tat_028"},
        {"mphipster_overlays", "FM_Hip_M_Tat_029"},
        {"mphipster_overlays", "FM_Hip_M_Tat_030"},
        {"mphipster_overlays", "FM_Hip_M_Tat_031"},
        {"mphipster_overlays", "FM_Hip_M_Tat_032"},
        {"mphipster_overlays", "FM_Hip_M_Tat_033"},
        {"mphipster_overlays", "FM_Hip_M_Tat_034"},
        {"mphipster_overlays", "FM_Hip_M_Tat_035"},
        {"mphipster_overlays", "FM_Hip_M_Tat_036"},
        {"mphipster_overlays", "FM_Hip_M_Tat_037"},
        {"mphipster_overlays", "FM_Hip_M_Tat_038"},
        {"mphipster_overlays", "FM_Hip_M_Tat_039"},
        {"mphipster_overlays", "FM_Hip_M_Tat_040"},
        {"mphipster_overlays", "FM_Hip_M_Tat_041"},
        {"mphipster_overlays", "FM_Hip_M_Tat_042"},
        {"mphipster_overlays", "FM_Hip_M_Tat_043"},
        {"mphipster_overlays", "FM_Hip_M_Tat_044"},
        {"mphipster_overlays", "FM_Hip_M_Tat_045"},
        {"mphipster_overlays", "FM_Hip_M_Tat_046"},
        {"mphipster_overlays", "FM_Hip_M_Tat_047"},
        {"mphipster_overlays", "FM_Hip_M_Tat_048"},
        {"mphipster_overlays", "FM_Hip_F_Tat_000"},
        {"mphipster_overlays", "FM_Hip_F_Tat_001"},
        {"mphipster_overlays", "FM_Hip_F_Tat_002"},
        {"mphipster_overlays", "FM_Hip_F_Tat_003"},
        {"mphipster_overlays", "FM_Hip_F_Tat_004"},
        {"mphipster_overlays", "FM_Hip_F_Tat_005"},
        {"mphipster_overlays", "FM_Hip_F_Tat_006"},
        {"mphipster_overlays", "FM_Hip_F_Tat_007"},
        {"mphipster_overlays", "FM_Hip_F_Tat_008"},
        {"mphipster_overlays", "FM_Hip_F_Tat_009"},
        {"mphipster_overlays", "FM_Hip_F_Tat_010"},
        {"mphipster_overlays", "FM_Hip_F_Tat_011"},
        {"mphipster_overlays", "FM_Hip_F_Tat_012"},
        {"mphipster_overlays", "FM_Hip_F_Tat_013"},
        {"mphipster_overlays", "FM_Hip_F_Tat_014"},
        {"mphipster_overlays", "FM_Hip_F_Tat_015"},
        {"mphipster_overlays", "FM_Hip_F_Tat_016"},
        {"mphipster_overlays", "FM_Hip_F_Tat_017"},
        {"mphipster_overlays", "FM_Hip_F_Tat_018"},
        {"mphipster_overlays", "FM_Hip_F_Tat_019"},
        {"mphipster_overlays", "FM_Hip_F_Tat_020"},
        {"mphipster_overlays", "FM_Hip_F_Tat_021"},
        {"mphipster_overlays", "FM_Hip_F_Tat_022"},
        {"mphipster_overlays", "FM_Hip_F_Tat_023"},
        {"mphipster_overlays", "FM_Hip_F_Tat_024"},
        {"mphipster_overlays", "FM_Hip_F_Tat_025"},
        {"mphipster_overlays", "FM_Hip_F_Tat_026"},
        {"mphipster_overlays", "FM_Hip_F_Tat_027"},
        {"mphipster_overlays", "FM_Hip_F_Tat_028"},
        {"mphipster_overlays", "FM_Hip_F_Tat_029"},
        {"mphipster_overlays", "FM_Hip_F_Tat_030"},
        {"mphipster_overlays", "FM_Hip_F_Tat_031"},
        {"mphipster_overlays", "FM_Hip_F_Tat_032"},
        {"mphipster_overlays", "FM_Hip_F_Tat_033"},
        {"mphipster_overlays", "FM_Hip_F_Tat_034"},
        {"mphipster_overlays", "FM_Hip_F_Tat_035"},
        {"mphipster_overlays", "FM_Hip_F_Tat_036"},
        {"mphipster_overlays", "FM_Hip_F_Tat_037"},
        {"mphipster_overlays", "FM_Hip_F_Tat_038"},
        {"mphipster_overlays", "FM_Hip_F_Tat_039"},
        {"mphipster_overlays", "FM_Hip_F_Tat_040"},
        {"mphipster_overlays", "FM_Hip_F_Tat_041"},
        {"mphipster_overlays", "FM_Hip_F_Tat_042"},
        {"mphipster_overlays", "FM_Hip_F_Tat_043"},
        {"mphipster_overlays", "FM_Hip_F_Tat_044"},
        {"mphipster_overlays", "FM_Hip_F_Tat_045"},
        {"mphipster_overlays", "FM_Hip_F_Tat_046"},
        {"mphipster_overlays", "FM_Hip_F_Tat_047"},
        {"mphipster_overlays", "FM_Hip_F_Tat_048"},
        {"mphipster_overlays", "FM_F_Hair_017_a"},
        {"mphipster_overlays", "FM_F_Hair_017_b"},
        {"mphipster_overlays", "FM_F_Hair_017_c"},
        {"mphipster_overlays", "FM_F_Hair_017_d"},
        {"mphipster_overlays", "FM_F_Hair_017_e"},
        {"mphipster_overlays", "FM_F_Hair_020_a"},
        {"mphipster_overlays", "FM_F_Hair_020_b"},
        {"mphipster_overlays", "FM_F_Hair_020_c"},
        {"mphipster_overlays", "FM_F_Hair_020_d"},
        {"mphipster_overlays", "FM_F_Hair_020_e"},
        {"mphipster_overlays", "FM_Disc_M_Hair_001_a"},
        {"mphipster_overlays", "FM_Disc_M_Hair_001_b"},
        {"mphipster_overlays", "FM_Disc_M_Hair_001_c"},
        {"mphipster_overlays", "FM_Disc_M_Hair_001_d"},
        {"mphipster_overlays", "FM_Disc_M_Hair_001_e"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_000_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_000_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_001_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_001_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_002_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_002_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_003_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_003_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_004_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_004_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_005_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_005_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_006_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_006_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_007_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_007_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_008_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_008_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_009_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_009_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_010_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_010_F"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_011_M"},
        {"mpimportexport_overlays", "MP_MP_ImportExport_Tat_011_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_000_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_003_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_006_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_008_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_011_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_012_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_016_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_018_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_019_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_022_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_028_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_029_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_030_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_031_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_032_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_035_M"},
        {"mplowrider2_overlays", "MP_LR_Tat_000_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_003_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_006_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_008_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_011_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_012_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_016_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_018_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_019_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_022_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_028_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_029_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_030_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_031_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_032_F"},
        {"mplowrider2_overlays", "MP_LR_Tat_035_F"},
        {"mplowrider2_overlays", "LR_F_Hair_003"},
        {"mplowrider2_overlays", "LR_F_Hair_004"},
        {"mplowrider2_overlays", "LR_F_Hair_006"},
        {"mplowrider2_overlays", "LR_M_Hair_004"},
        {"mplowrider2_overlays", "LR_M_Hair_005"},
        {"mplowrider2_overlays", "LR_M_Hair_006"},
        {"mplowrider_overlays", "MP_LR_Tat_001_M"},
        {"mplowrider_overlays", "MP_LR_Tat_002_M"},
        {"mplowrider_overlays", "MP_LR_Tat_004_M"},
        {"mplowrider_overlays", "MP_LR_Tat_005_M"},
        {"mplowrider_overlays", "MP_LR_Tat_007_M"},
        {"mplowrider_overlays", "MP_LR_Tat_009_M"},
        {"mplowrider_overlays", "MP_LR_Tat_010_M"},
        {"mplowrider_overlays", "MP_LR_Tat_013_M"},
        {"mplowrider_overlays", "MP_LR_Tat_014_M"},
        {"mplowrider_overlays", "MP_LR_Tat_015_M"},
        {"mplowrider_overlays", "MP_LR_Tat_017_M"},
        {"mplowrider_overlays", "MP_LR_Tat_020_M"},
        {"mplowrider_overlays", "MP_LR_Tat_021_M"},
        {"mplowrider_overlays", "MP_LR_Tat_023_M"},
        {"mplowrider_overlays", "MP_LR_Tat_026_M"},
        {"mplowrider_overlays", "MP_LR_Tat_027_M"},
        {"mplowrider_overlays", "MP_LR_Tat_033_M"},
        {"mplowrider_overlays", "MP_LR_Tat_001_F"},
        {"mplowrider_overlays", "MP_LR_Tat_002_F"},
        {"mplowrider_overlays", "MP_LR_Tat_004_F"},
        {"mplowrider_overlays", "MP_LR_Tat_005_F"},
        {"mplowrider_overlays", "MP_LR_Tat_007_F"},
        {"mplowrider_overlays", "MP_LR_Tat_009_F"},
        {"mplowrider_overlays", "MP_LR_Tat_010_F"},
        {"mplowrider_overlays", "MP_LR_Tat_013_F"},
        {"mplowrider_overlays", "MP_LR_Tat_014_F"},
        {"mplowrider_overlays", "MP_LR_Tat_015_F"},
        {"mplowrider_overlays", "MP_LR_Tat_017_F"},
        {"mplowrider_overlays", "MP_LR_Tat_020_F"},
        {"mplowrider_overlays", "MP_LR_Tat_021_F"},
        {"mplowrider_overlays", "MP_LR_Tat_023_F"},
        {"mplowrider_overlays", "MP_LR_Tat_026_F"},
        {"mplowrider_overlays", "MP_LR_Tat_027_F"},
        {"mplowrider_overlays", "MP_LR_Tat_033_F"},
        {"mplowrider_overlays", "LR_F_Hair_000"},
        {"mplowrider_overlays", "LR_F_Hair_001"},
        {"mplowrider_overlays", "LR_F_Hair_002"},
        {"mplowrider_overlays", "LR_M_Hair_000"},
        {"mplowrider_overlays", "LR_M_Hair_001"},
        {"mplowrider_overlays", "LR_M_Hair_002"},
        {"mplowrider_overlays", "LR_M_Hair_003"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_002_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_005_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_010_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_011_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_012_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_016_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_017_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_018_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_022_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_023_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_025_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_026_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_027_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_028_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_029_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_030_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_031_M"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_002_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_005_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_010_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_011_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_012_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_016_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_017_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_018_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_022_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_023_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_025_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_026_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_027_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_028_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_029_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_030_F"},
        {"mpluxe2_overlays", "MP_LUXE_TAT_031_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_000_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_001_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_003_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_004_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_006_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_007_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_008_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_009_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_013_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_014_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_015_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_019_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_020_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_021_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_024_M"},
        {"mpluxe_overlays", "MP_LUXE_TAT_000_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_001_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_003_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_004_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_006_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_007_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_008_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_009_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_013_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_014_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_015_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_019_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_020_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_021_F"},
        {"mpluxe_overlays", "MP_LUXE_TAT_024_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_000_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_000_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_001_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_001_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_002_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_002_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_003_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_003_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_004_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_004_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_005_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_005_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_006_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_006_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_007_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_007_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_008_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_008_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_009_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_009_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_010_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_010_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_011_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_011_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_012_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_012_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_013_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_013_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_014_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_014_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_015_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_015_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_016_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_016_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_017_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_017_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_018_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_018_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_019_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_019_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_020_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_020_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_021_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_021_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_022_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_022_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_023_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_023_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_024_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_024_F"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_025_M"},
        {"mpsmuggler_overlays", "MP_Smuggler_Tattoo_025_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_Tat_000_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_001_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_002_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_003_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_004_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_005_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_006_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_007_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_008_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_009_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_010_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_011_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_012_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_013_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_014_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_015_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_016_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_017_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_018_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_019_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_020_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_021_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_022_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_023_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_024_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_025_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_026_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_027_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_028_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_029_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_030_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_031_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_032_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_033_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_034_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_035_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_036_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_037_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_038_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_039_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_040_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_041_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_042_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_043_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_044_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_045_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_046_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_047_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_048_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_049_M"},
        {"mpstunt_overlays", "MP_MP_Stunt_Tat_000_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_001_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_002_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_003_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_004_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_005_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_006_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_007_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_008_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_009_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_010_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_011_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_012_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_013_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_014_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_015_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_016_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_017_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_018_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_019_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_020_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_021_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_022_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_023_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_024_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_025_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_026_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_027_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_028_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_029_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_030_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_031_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_032_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_033_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_034_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_035_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_036_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_037_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_038_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_039_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_040_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_041_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_042_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_043_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_044_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_045_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_046_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_047_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_048_F"},
        {"mpstunt_overlays", "MP_MP_Stunt_tat_049_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Hair_M_000_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Hair_F_000_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_000_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_000_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_001_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_001_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_002_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_002_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_003_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_003_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_004_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_004_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_005_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_005_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_006_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_006_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_007_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_007_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_008_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_008_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_009_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_009_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_010_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_010_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_011_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_011_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_012_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_012_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_013_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_013_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_014_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_014_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_015_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_015_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_016_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_016_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_017_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_017_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_018_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_018_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_019_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_019_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_020_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_020_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_021_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_021_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_022_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_022_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_023_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_023_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_024_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_024_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_025_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_025_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_026_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_026_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_027_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_027_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_028_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_028_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_029_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_029_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_030_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_030_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_031_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_031_F"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_032_M"},
        {"mpvinewood_overlays", "MP_Vinewood_Tat_032_F"},
        {"mpxmas_604490_overlays", "Hair_014_Fix"},
        {"multiplayer_overlays", "FM_Tat_Award_M_000"},
        {"multiplayer_overlays", "FM_Tat_Award_M_001"},
        {"multiplayer_overlays", "FM_Tat_Award_M_002"},
        {"multiplayer_overlays", "FM_Tat_Award_M_003"},
        {"multiplayer_overlays", "FM_Tat_Award_M_004"},
        {"multiplayer_overlays", "FM_Tat_Award_M_005"},
        {"multiplayer_overlays", "FM_Tat_Award_M_006"},
        {"multiplayer_overlays", "FM_Tat_Award_M_007"},
        {"multiplayer_overlays", "FM_Tat_Award_M_008"},
        {"multiplayer_overlays", "FM_Tat_Award_M_009"},
        {"multiplayer_overlays", "FM_Tat_Award_M_010"},
        {"multiplayer_overlays", "FM_Tat_Award_M_011"},
        {"multiplayer_overlays", "FM_Tat_Award_M_012"},
        {"multiplayer_overlays", "FM_Tat_Award_M_013"},
        {"multiplayer_overlays", "FM_Tat_Award_M_014"},
        {"multiplayer_overlays", "FM_Tat_Award_M_015"},
        {"multiplayer_overlays", "FM_Tat_Award_M_016"},
        {"multiplayer_overlays", "FM_Tat_Award_M_017"},
        {"multiplayer_overlays", "FM_Tat_Award_M_018"},
        {"multiplayer_overlays", "FM_Tat_Award_M_019"},
        {"multiplayer_overlays", "FM_Tat_M_000"},
        {"multiplayer_overlays", "FM_Tat_M_001"},
        {"multiplayer_overlays", "FM_Tat_M_002"},
        {"multiplayer_overlays", "FM_Tat_M_003"},
        {"multiplayer_overlays", "FM_Tat_M_004"},
        {"multiplayer_overlays", "FM_Tat_M_005"},
        {"multiplayer_overlays", "FM_Tat_M_006"},
        {"multiplayer_overlays", "FM_Tat_M_007"},
        {"multiplayer_overlays", "FM_Tat_M_008"},
        {"multiplayer_overlays", "FM_Tat_M_009"},
        {"multiplayer_overlays", "FM_Tat_M_010"},
        {"multiplayer_overlays", "FM_Tat_M_011"},
        {"multiplayer_overlays", "FM_Tat_M_012"},
        {"multiplayer_overlays", "FM_Tat_M_013"},
        {"multiplayer_overlays", "FM_Tat_M_014"},
        {"multiplayer_overlays", "FM_Tat_M_015"},
        {"multiplayer_overlays", "FM_Tat_M_016"},
        {"multiplayer_overlays", "FM_Tat_M_017"},
        {"multiplayer_overlays", "FM_Tat_M_018"},
        {"multiplayer_overlays", "FM_Tat_M_019"},
        {"multiplayer_overlays", "FM_Tat_M_020"},
        {"multiplayer_overlays", "FM_Tat_M_021"},
        {"multiplayer_overlays", "FM_Tat_M_022"},
        {"multiplayer_overlays", "FM_Tat_M_023"},
        {"multiplayer_overlays", "FM_Tat_M_024"},
        {"multiplayer_overlays", "FM_Tat_M_025"},
        {"multiplayer_overlays", "FM_Tat_M_026"},
        {"multiplayer_overlays", "FM_Tat_M_027"},
        {"multiplayer_overlays", "FM_Tat_M_028"},
        {"multiplayer_overlays", "FM_Tat_M_029"},
        {"multiplayer_overlays", "FM_Tat_M_030"},
        {"multiplayer_overlays", "FM_Tat_M_031"},
        {"multiplayer_overlays", "FM_Tat_M_032"},
        {"multiplayer_overlays", "FM_Tat_M_033"},
        {"multiplayer_overlays", "FM_Tat_M_034"},
        {"multiplayer_overlays", "FM_Tat_M_035"},
        {"multiplayer_overlays", "FM_Tat_M_036"},
        {"multiplayer_overlays", "FM_Tat_M_037"},
        {"multiplayer_overlays", "FM_Tat_M_038"},
        {"multiplayer_overlays", "FM_Tat_M_039"},
        {"multiplayer_overlays", "FM_Tat_M_040"},
        {"multiplayer_overlays", "FM_Tat_M_041"},
        {"multiplayer_overlays", "FM_Tat_M_042"},
        {"multiplayer_overlays", "FM_Tat_M_043"},
        {"multiplayer_overlays", "FM_Tat_M_044"},
        {"multiplayer_overlays", "FM_Tat_M_045"},
        {"multiplayer_overlays", "FM_Tat_M_046"},
        {"multiplayer_overlays", "FM_Tat_M_047"},
        {"multiplayer_overlays", "FM_Tat_Award_F_000"},
        {"multiplayer_overlays", "FM_Tat_Award_F_001"},
        {"multiplayer_overlays", "FM_Tat_Award_F_002"},
        {"multiplayer_overlays", "FM_Tat_Award_F_003"},
        {"multiplayer_overlays", "FM_Tat_Award_F_004"},
        {"multiplayer_overlays", "FM_Tat_Award_F_005"},
        {"multiplayer_overlays", "FM_Tat_Award_F_006"},
        {"multiplayer_overlays", "FM_Tat_Award_F_007"},
        {"multiplayer_overlays", "FM_Tat_Award_F_008"},
        {"multiplayer_overlays", "FM_Tat_Award_F_009"},
        {"multiplayer_overlays", "FM_Tat_Award_F_010"},
        {"multiplayer_overlays", "FM_Tat_Award_F_011"},
        {"multiplayer_overlays", "FM_Tat_Award_F_012"},
        {"multiplayer_overlays", "FM_Tat_Award_F_013"},
        {"multiplayer_overlays", "FM_Tat_Award_F_014"},
        {"multiplayer_overlays", "FM_Tat_Award_F_015"},
        {"multiplayer_overlays", "FM_Tat_Award_F_016"},
        {"multiplayer_overlays", "FM_Tat_Award_F_017"},
        {"multiplayer_overlays", "FM_Tat_Award_F_018"},
        {"multiplayer_overlays", "FM_Tat_Award_F_019"},
        {"multiplayer_overlays", "FM_Tat_F_001"},
        {"multiplayer_overlays", "FM_Tat_F_002"},
        {"multiplayer_overlays", "FM_Tat_F_003"},
        {"multiplayer_overlays", "FM_Tat_F_004"},
        {"multiplayer_overlays", "FM_Tat_F_005"},
        {"multiplayer_overlays", "FM_Tat_F_006"},
        {"multiplayer_overlays", "FM_Tat_F_007"},
        {"multiplayer_overlays", "FM_Tat_F_008"},
        {"multiplayer_overlays", "FM_Tat_F_009"},
        {"multiplayer_overlays", "FM_Tat_F_010"},
        {"multiplayer_overlays", "FM_Tat_F_011"},
        {"multiplayer_overlays", "FM_Tat_F_012"},
        {"multiplayer_overlays", "FM_Tat_F_013"},
        {"multiplayer_overlays", "FM_Tat_F_014"},
        {"multiplayer_overlays", "FM_Tat_F_015"},
        {"multiplayer_overlays", "FM_Tat_F_016"},
        {"multiplayer_overlays", "FM_Tat_F_017"},
        {"multiplayer_overlays", "FM_Tat_F_018"},
        {"multiplayer_overlays", "FM_Tat_F_019"},
        {"multiplayer_overlays", "FM_Tat_F_020"},
        {"multiplayer_overlays", "FM_Tat_F_021"},
        {"multiplayer_overlays", "FM_Tat_F_022"},
        {"multiplayer_overlays", "FM_Tat_F_023"},
        {"multiplayer_overlays", "FM_Tat_F_024"},
        {"multiplayer_overlays", "FM_Tat_F_025"},
        {"multiplayer_overlays", "FM_Tat_F_026"},
        {"multiplayer_overlays", "FM_Tat_F_027"},
        {"multiplayer_overlays", "FM_Tat_F_028"},
        {"multiplayer_overlays", "FM_Tat_F_029"},
        {"multiplayer_overlays", "FM_Tat_F_030"},
        {"multiplayer_overlays", "FM_Tat_F_031"},
        {"multiplayer_overlays", "FM_Tat_F_032"},
        {"multiplayer_overlays", "FM_Tat_F_033"},
        {"multiplayer_overlays", "FM_Tat_F_034"},
        {"multiplayer_overlays", "FM_Tat_F_035"},
        {"multiplayer_overlays", "FM_Tat_F_036"},
        {"multiplayer_overlays", "FM_Tat_F_037"},
        {"multiplayer_overlays", "FM_Tat_F_038"},
        {"multiplayer_overlays", "FM_Tat_F_039"},
        {"multiplayer_overlays", "FM_Tat_F_040"},
        {"multiplayer_overlays", "FM_Tat_F_041"},
        {"multiplayer_overlays", "FM_Tat_F_042"},
        {"multiplayer_overlays", "FM_Tat_F_043"},
        {"multiplayer_overlays", "FM_Tat_F_044"},
        {"multiplayer_overlays", "FM_Tat_F_045"},
        {"multiplayer_overlays", "FM_Tat_F_046"},
        {"multiplayer_overlays", "FM_Tat_F_047"},
        {"multiplayer_overlays", "FM_F_Hair_003_a"},
        {"multiplayer_overlays", "FM_F_Hair_003_b"},
        {"multiplayer_overlays", "FM_F_Hair_003_c"},
        {"multiplayer_overlays", "FM_F_Hair_003_d"},
        {"multiplayer_overlays", "FM_F_Hair_003_e"},
        {"multiplayer_overlays", "FM_F_Hair_005_a"},
        {"multiplayer_overlays", "FM_F_Hair_005_b"},
        {"multiplayer_overlays", "FM_F_Hair_005_c"},
        {"multiplayer_overlays", "FM_F_Hair_005_d"},
        {"multiplayer_overlays", "FM_F_Hair_005_e"},
        {"multiplayer_overlays", "FM_F_Hair_006_a"},
        {"multiplayer_overlays", "FM_F_Hair_006_b"},
        {"multiplayer_overlays", "FM_F_Hair_006_c"},
        {"multiplayer_overlays", "FM_F_Hair_006_d"},
        {"multiplayer_overlays", "FM_F_Hair_006_e"},
        {"multiplayer_overlays", "FM_F_Hair_013_a"},
        {"multiplayer_overlays", "FM_F_Hair_013_b"},
        {"multiplayer_overlays", "FM_F_Hair_013_c"},
        {"multiplayer_overlays", "FM_F_Hair_013_d"},
        {"multiplayer_overlays", "FM_F_Hair_013_e"},
        {"multiplayer_overlays", "FM_F_Hair_014_a"},
        {"multiplayer_overlays", "FM_F_Hair_014_b"},
        {"multiplayer_overlays", "FM_F_Hair_014_c"},
        {"multiplayer_overlays", "FM_F_Hair_014_d"},
        {"multiplayer_overlays", "FM_F_Hair_014_e"},
        {"multiplayer_overlays", "FM_F_Hair_long_a"},
        {"multiplayer_overlays", "FM_F_Hair_long_b"},
        {"multiplayer_overlays", "FM_F_Hair_long_c"},
        {"multiplayer_overlays", "FM_F_Hair_long_d"},
        {"multiplayer_overlays", "FM_F_Hair_long_e"},
        {"multiplayer_overlays", "FM_M_Hair_001_a"},
        {"multiplayer_overlays", "FM_M_Hair_001_b"},
        {"multiplayer_overlays", "FM_M_Hair_001_c"},
        {"multiplayer_overlays", "FM_M_Hair_001_d"},
        {"multiplayer_overlays", "FM_M_Hair_001_e"},
        {"multiplayer_overlays", "FM_M_Hair_003_a"},
        {"multiplayer_overlays", "FM_M_Hair_003_b"},
        {"multiplayer_overlays", "FM_M_Hair_003_c"},
        {"multiplayer_overlays", "FM_M_Hair_003_d"},
        {"multiplayer_overlays", "FM_M_Hair_003_e"},
        {"multiplayer_overlays", "FM_M_Hair_006_a"},
        {"multiplayer_overlays", "FM_M_Hair_006_b"},
        {"multiplayer_overlays", "FM_M_Hair_006_c"},
        {"multiplayer_overlays", "FM_M_Hair_006_d"},
        {"multiplayer_overlays", "FM_M_Hair_006_e"},
        {"multiplayer_overlays", "FM_M_Hair_008_a"},
        {"multiplayer_overlays", "FM_M_Hair_008_b"},
        {"multiplayer_overlays", "FM_M_Hair_008_c"},
        {"multiplayer_overlays", "FM_M_Hair_008_d"},
        {"multiplayer_overlays", "FM_M_Hair_008_e"},
        {"multiplayer_overlays", "FM_M_Hair_long_a"},
        {"multiplayer_overlays", "FM_M_Hair_long_b"},
        {"multiplayer_overlays", "FM_M_Hair_long_c"},
        {"multiplayer_overlays", "FM_M_Hair_long_d"},
        {"multiplayer_overlays", "FM_M_Hair_long_e"},
        {"multiplayer_overlays", "NG_M_Hair_001"},
        {"multiplayer_overlays", "NG_M_Hair_002"},
        {"multiplayer_overlays", "NG_M_Hair_003"},
        {"multiplayer_overlays", "NG_M_Hair_004"},
        {"multiplayer_overlays", "NG_M_Hair_005"},
        {"multiplayer_overlays", "NG_M_Hair_006"},
        {"multiplayer_overlays", "NG_M_Hair_007"},
        {"multiplayer_overlays", "NG_M_Hair_008"},
        {"multiplayer_overlays", "NG_M_Hair_009"},
        {"multiplayer_overlays", "NG_M_Hair_010"},
        {"multiplayer_overlays", "NG_M_Hair_011"},
        {"multiplayer_overlays", "NG_M_Hair_012"},
        {"multiplayer_overlays", "NG_M_Hair_013"},
        {"multiplayer_overlays", "NG_M_Hair_014"},
        {"multiplayer_overlays", "NG_M_Hair_015"},
        {"multiplayer_overlays", "NGBea_M_Hair_000"},
        {"multiplayer_overlays", "NGBea_M_Hair_001"},
        {"multiplayer_overlays", "NGBus_M_Hair_000"},
        {"multiplayer_overlays", "NGBus_M_Hair_001"},
        {"multiplayer_overlays", "NGHip_M_Hair_000"},
        {"multiplayer_overlays", "NGHip_M_Hair_001"},
        {"multiplayer_overlays", "NGInd_M_Hair_000"},
        {"multiplayer_overlays", "NG_F_Hair_001"},
        {"multiplayer_overlays", "NG_F_Hair_002"},
        {"multiplayer_overlays", "NG_F_Hair_003"},
        {"multiplayer_overlays", "NG_F_Hair_004"},
        {"multiplayer_overlays", "NG_F_Hair_005"},
        {"multiplayer_overlays", "NG_F_Hair_006"},
        {"multiplayer_overlays", "NG_F_Hair_007"},
        {"multiplayer_overlays", "NG_F_Hair_008"},
        {"multiplayer_overlays", "NG_F_Hair_009"},
        {"multiplayer_overlays", "NG_F_Hair_010"},
        {"multiplayer_overlays", "NG_F_Hair_011"},
        {"multiplayer_overlays", "NG_F_Hair_012"},
        {"multiplayer_overlays", "NG_F_Hair_013"},
        {"multiplayer_overlays", "NG_F_Hair_014"},
        {"multiplayer_overlays", "NG_F_Hair_015"},
        {"multiplayer_overlays", "NGBea_F_Hair_000"},
        {"multiplayer_overlays", "NGBea_F_Hair_001"},
        {"multiplayer_overlays", "NGBus_F_Hair_000"},
        {"multiplayer_overlays", "NGBus_F_Hair_001"},
        {"multiplayer_overlays", "NGHip_F_Hair_000"},
        {"multiplayer_overlays", "NGHip_F_Hair_001"},
        {"multiplayer_overlays", "NGInd_F_Hair_000"},
    },
}