Config = {}

Config.Locale = 'fr'

Config.Accounts = {
	bank = _U('account_bank'),
	black_money = _U('account_black_money'),
	money = _U('account_money')
}

Config.StartingAccountMoney = {money = 1500, bank = 0}

Config.MaxWeight            = 45000
Config.PaycheckInterval     = 15 * 60000
Config.EnableDebug          = true
Config.PrimaryIdentifier	= "steam"

Config.Item = {
    {'WEAPON_HEAVYPISTOL', 'w_pi_heavypistol_luxe'},
    {'WEAPON_FLASHLIGHT', 'w_me_flashlight'},
    {'WEAPON_DAGGER', 'w_me_dagger'},
    {'WEAPON_CROWBAR', 'w_me_crowbar'},
    {'WEAPON_BOTTLE', 'w_me_bottle'},
    {'WEAPON_KNIFE', 'prop_w_me_knife_01'},
    {'WEAPON_BAT', 'w_me_bat'},
    {'WEAPON_MACHETE', 'prop_ld_w_me_machette'},
    {'WEAPON_GOLFCLUB', 'w_me_gclub'},
    {'WEAPON_KNUCKLE', 'w_me_knuckle'},
    {'WEAPON_HAMMER', 'w_me_hammer'},
    {'WEAPON_HATCHET', 'w_me_hatchet'},
    {'WEAPON_POOLCUE', 'w_me_poolcue'},
    {'WEAPON_WRENCH', 'w_me_wrench'},
    {'WEAPON_NIGHTSTICK', 'w_me_nightstick'},
    {'WEAPON_SWITCHBLADE', 'w_me_switchblade'},
    {'WEAPON_FLAREGUN', 'w_pi_flaregun'},
    {'WEAPON_APPISTOL', 'w_pi_appistol'},
    {'WEAPON_COMBATPISTOL', 'w_pi_combatpistol'},
    {'WEAPON_PISTOL', 'w_pi_pistol'},
    {'WEAPON_PISTOL50', 'w_pi_pistol50'},
    {'WEAPON_SNSPISTOL', 'w_pi_sns_pistol'},
    {'WEAPON_STUNGUN', 'w_pi_stungun'},

    {'WEAPON_VINTAGEPISTOL', 'w_pi_vintage_pistol'},
    {'WEAPON_ASSAULTSHOTGUN', 'w_sg_assaultshotgun'},
    {'WEAPON_BULLPUPSHOTGUN', 'w_sg_bullpupshotgun'},
    {'WEAPON_PUMPSHOTGUN', 'w_sg_pumpshotgun'},
    {'WEAPON_SAWNOFFSHOTGUN', 'w_sg_sawnoff'},
    {'WEAPON_MICROSMG', 'w_sb_microsmg'},
    {'WEAPON_SMG', 'w_sb_smg'},
    {'WEAPON_ASSAULTSMG', 'w_sb_assaultsmg'},
    {'WEAPON_ASSAULTRIFLE', 'w_ar_assaultrifle'},

    {'ammo_pistol', 'prop_ld_ammo_pack_01'},
    {'ammo_shotgun', 'prop_ld_ammo_pack_02'},
    {'ammo_smg', 'prop_ld_ammo_pack_03'},
    {'ammo_smg_large', 'prop_ld_ammo_pack_03'},
    {'ammo_rifle', 'prop_ld_ammo_pack_03'},
    {'ammo_snp', 'prop_box_ammo01a'},

    {'candybox', 'prop_candy_pqs'},
    {'bolnoixcajou', 'prop_candy_pqs'},
    {'bolpistache', 'prop_candy_pqs'},
    {'bolcacahuetes', 'prop_candy_pqs'},
    {'bolchips', 'prop_candy_pqs'},
    {'p&qs', 'prop_candy_pqs'},

    {'vodka', 'ba_prop_battle_whiskey_bottle_s'},
    {'cocktail', 'ba_prop_battle_whiskey_bottle_s'},
    {'chocolat', 'prop_choc_ego'},
    {'beef', 'prop_sandwich_01'},

    {'bread', 'prop_sandwich_01'},
    {'water', 'prop_ld_flow_bottle'},
    {'sprunk', 'prop_ld_can_01'},
    {'ecola', 'prop_ecola_can'},
    {'blue_phone', 'prop_phone_ing'},
    {'radio', 'prop_cs_hand_radio'},
    {'hamburger', 'prop_cs_burger_01'},
    {'moteur', 'prop_car_engine_01'},
    {'crochetage', 'prop_tool_screwdvr01'},
    {'carte', 'ch_prop_swipe_card_01c'},

    {'coke', 'prop_coke_block_01'},
    {'weed', 'prop_weed_block_01'},
    {'meth', 'bkr_prop_meth_openbag_01a'},

    {'hei_prop_yah_table_01', 'hei_prop_yah_table_01'},
    {'hei_prop_yah_table_03', 'hei_prop_yah_table_03'},
    {'prop_chateau_table_01', 'prop_chateau_table_01'},
    {'prop_patio_lounger1_table', 'prop_patio_lounger1_table'},
    {'prop_proxy_chateau_table', 'prop_proxy_chateau_table'},
    {'prop_rub_table_02', 'prop_rub_table_02'},
    {'prop_rub_table_01', 'prop_rub_table_01'},
    {'prop_table_01', 'prop_table_01'},
    {'prop_table_02', 'prop_table_02'},
    {'prop_table_03', 'prop_table_03'},
    {'prop_table_04', 'prop_table_04'},
    {'prop_table_05', 'prop_table_05'},
    {'prop_table_06', 'prop_table_06'},
    {'prop_table_07', 'prop_table_07'},
    {'prop_table_08', 'prop_table_08'},
    {'prop_ven_market_table1', 'prop_ven_market_table1'},
    {'prop_yacht_table_01', 'prop_yacht_table_01'},
    {'prop_yacht_table_02', 'prop_yacht_table_02'},
    {'v_ret_fh_dinetable', 'v_ret_fh_dinetable'},
    {'v_ret_fh_dinetble', 'v_ret_fh_dinetble'},
    {'v_res_mconsoletrad', 'v_res_mconsoletrad'},
    {'prop_rub_table_02', 'prop_rub_table_02'},
    {'ba_prop_int_trad_table', 'ba_prop_int_trad_table'},
    {'xm_prop_x17_desk_cover_01a', 'xm_prop_x17_desk_cover_01a'},
    {'xm_prop_lab_desk_02', 'xm_prop_lab_desk_02'},
    {'xm_prop_lab_desk_01', 'xm_prop_lab_desk_01'},
    {'ex_mp_h_din_table_05', 'ex_mp_h_din_table_05'},
    {'hei_prop_yah_table_02', 'hei_prop_yah_table_02'},
    {'prop_ld_farm_table02', 'prop_ld_farm_table02'},
    {'prop_t_coffe_table', 'prop_t_coffe_table'},
    {'prop_t_coffe_table_02', 'prop_t_coffe_table_02'},

    {'prop_ld_greenscreen_01', 'prop_ld_greenscreen_01'},
    {'prop_tv_cam_02', 'prop_tv_cam_02'},

    {'p_pharm_unit_02', 'p_pharm_unit_02'},
    {'p_pharm_unit_01', 'p_pharm_unit_01'},
    {'p_v_43_safe_s', 'p_v_43_safe_s'},
    {'prop_bin_03a', 'prop_bin_03a'},
    {'prop_bin_07c', 'prop_bin_07c'},
    {'prop_bin_08open', 'prop_bin_08open'},
    {'prop_bin_10a', 'prop_bin_10a'},
    {'prop_devin_box_01', 'prop_devin_box_01'},
    {'prop_ld_int_safe_01', 'prop_ld_int_safe_01'},
    {'prop_dress_disp_01', 'prop_dress_disp_01'},
    {'prop_dress_disp_02', 'prop_dress_disp_02'},
    {'prop_dress_disp_03', 'prop_dress_disp_03'},
    {'prop_dress_disp_04', 'prop_dress_disp_04'},
    {'v_ret_fh_displayc', 'v_ret_fh_displayc'},

    {'apa_mp_h_bed_double_08', 'apa_mp_h_bed_double_08'},
    {'apa_mp_h_bed_double_09', 'apa_mp_h_bed_double_09'},
    {'apa_mp_h_bed_wide_05', 'apa_mp_h_bed_wide_05'},
    {'imp_prop_impexp_sofabed_01a', 'imp_prop_impexp_sofabed_01a'},
    {'apa_mp_h_bed_with_table_02', 'apa_mp_h_bed_with_table_02'},
    {'bka_prop_biker_campbed_01', 'bka_prop_biker_campbed_01'},
    {'apa_mp_h_yacht_bed_01', 'apa_mp_h_yacht_bed_01'},
    {'apa_mp_h_yacht_bed_02', 'apa_mp_h_yacht_bed_02'},
    {'p_lestersbed_s', 'p_lestersbed_s'},
    {'p_mbbed_s', 'p_mbbed_s'},
    {'v_res_d_bed', 'v_res_d_bed'},
    {'v_res_tre_bed2', 'v_res_tre_bed2'},
    {'v_res_tre_bed1', 'v_res_tre_bed1'},
    {'v_res_mdbed', 'v_res_mdbed'},
    {'v_res_msonbed', 'v_res_msonbed'},
    {'v_res_tt_bed', 'v_res_tt_bed'},

    {'prop_barrier_work05', 'prop_barrier_work05'},
    {'prop_boxpile_07d', 'prop_boxpile_07d'},
    {'prop_roadcone02a', 'prop_roadcone02a'},

    {'hei_prop_yah_lounger', 'hei_prop_yah_lounger'},
    {'hei_prop_yah_seat_01', 'hei_prop_yah_seat_01'},
    {'hei_prop_yah_seat_02', 'hei_prop_yah_seat_02'},
    {'hei_prop_yah_seat_03', 'hei_prop_yah_seat_03'},
    {'miss_rub_couch_01', 'miss_rub_couch_01'},
    {'p_armchair_01_s', 'p_armchair_01_s'},
    {'p_ilev_p_easychair_s', 'p_ilev_p_easychair_s'},
    {'p_lev_sofa_s', 'p_lev_sofa_s'},
    {'p_patio_lounger1_s', 'p_patio_lounger1_s'},
    {'p_res_sofa_l_s', 'p_res_sofa_l_s'},
    {'p_v_med_p_sofa_s', 'p_v_med_p_sofa_s'},
    {'prop_bench_01a', 'prop_bench_01a'},
    {'prop_bench_06', 'prop_bench_06'},
    {'prop_ld_farm_chair01', 'prop_ld_farm_chair01'},
    {'prop_ld_farm_couch01', 'prop_ld_farm_couch01'},
    {'prop_ld_farm_couch02', 'prop_ld_farm_couch02'},
    {'prop_rub_couch04', 'prop_rub_couch04'},
    {'prop_t_sofa', 'prop_t_sofa'},
    {'prop_t_sofa_02', 'prop_t_sofa_02'},
    {'v_ilev_m_sofa', 'v_ilev_m_sofa'},
    {'v_res_tre_sofa_s', 'v_res_tre_sofa_s'},
    {'v_tre_sofa_mess_a_s', 'v_tre_sofa_mess_a_s'},
    {'v_tre_sofa_mess_b_s', 'v_tre_sofa_mess_b_s'},
    {'v_tre_sofa_mess_c_s', 'v_tre_sofa_mess_c_s'},

    {'bkr_prop_duffel_bag_01a', 'bkr_prop_duffel_bag_01a'},
    {'v_med_emptybed', 'v_med_emptybed'},
    {'v_med_cor_emblmtable', 'v_med_cor_emblmtable'},
    {'v_ret_gc_bag01', 'v_ret_gc_bag01'},
    {'xm_prop_body_bag', 'xm_prop_body_bag'},

    {'lighter', 'p_cs_lighter_01'},
    {'redw', 'v_ret_ml_cigs2'},         ----- CIGARETTE
    {'redwcig', 'prop_cs_ciggy_01'},
    {'cubancigar', 'prop_cigar_02'},

    {'prop_chair_01a', 'prop_chair_01a'},
    {'prop_chair_01b', 'prop_chair_01b'},
    {'prop_chair_02', 'prop_chair_02'},
    {'prop_chair_03', 'prop_chair_03'},
    {'prop_chair_04', 'prop_chair_04'},
    {'prop_chair_05', 'prop_chair_05'},
    {'prop_chair_06', 'prop_chair_06'},
    {'prop_chair_07', 'prop_chair_07'},
    {'prop_chair_08', 'prop_chair_08'},
    {'prop_chair_09', 'prop_chair_09'},
    {'prop_chair_10', 'prop_chair_10'},
    {'apa_mp_h_din_chair_04', 'apa_mp_h_din_chair_04'},
    {'apa_mp_h_din_chair_08', 'apa_mp_h_din_chair_08'},
    {'apa_mp_h_din_chair_09', 'apa_mp_h_din_chair_09'},
    {'apa_mp_h_din_chair_12', 'apa_mp_h_din_chair_12'},
    {'apa_mp_h_stn_chairarm_01', 'apa_mp_h_stn_chairarm_01'},
    {'apa_mp_h_stn_chairarm_02', 'apa_mp_h_stn_chairarm_02'},
    {'apa_mp_h_stn_chairarm_09', 'apa_mp_h_stn_chairarm_09'},
    {'apa_mp_h_stn_chairarm_11', 'apa_mp_h_stn_chairarm_11'},
    {'apa_mp_h_stn_chairarm_12', 'apa_mp_h_stn_chairarm_12'},
    {'apa_mp_h_stn_chairarm_13', 'apa_mp_h_stn_chairarm_13'},
    {'apa_mp_h_stn_chairarm_23', 'apa_mp_h_stn_chairarm_23'},
    {'apa_mp_h_stn_chairarm_24', 'apa_mp_h_stn_chairarm_24'},
    {'apa_mp_h_stn_chairarm_25', 'apa_mp_h_stn_chairarm_25'},
    {'apa_mp_h_stn_chairarm_26', 'apa_mp_h_stn_chairarm_26'},
    {'apa_mp_h_stn_chairstrip_08', 'apa_mp_h_stn_chairstrip_08'},
    {'apa_mp_h_stn_chairstrip_04', 'apa_mp_h_stn_chairstrip_04'},
    {'apa_mp_h_stn_chairstrip_05', 'apa_mp_h_stn_chairstrip_05'},
    {'apa_mp_h_stn_chairstrip_06', 'apa_mp_h_stn_chairstrip_06'},
    {'apa_mp_h_yacht_armchair_03', 'apa_mp_h_yacht_armchair_03'},
    {'apa_mp_h_yacht_armchair_04', 'apa_mp_h_yacht_armchair_04'},
    {'ba_prop_battle_club_chair_02', 'ba_prop_battle_club_chair_02'},
    {'apa_mp_h_yacht_strip_chair_01', 'apa_mp_h_yacht_strip_chair_01'},
    {'ba_prop_battle_club_chair_01', 'ba_prop_battle_club_chair_01'},
    {'ba_prop_battle_club_chair_03', 'ba_prop_battle_club_chair_03'},
    {'bka_prop_biker_boardchair01', 'bka_prop_biker_boardchair01'},
    {'bka_prop_biker_chairstrip_01', 'bka_prop_biker_chairstrip_01'},
    {'bka_prop_biker_chairstrip_02', 'bka_prop_biker_chairstrip_02'},
    {'prop_barrier_work05', 'prop_barrier_work05'},
    {'prop_mp_cone_02', 'prop_mp_cone_02'},
    {'p_ld_stinger_s', 'p_ld_stinger_s'},
    {'item_kevlar', 'prop_bodyarmour_03'},
}

Config.ItemClothes = {
    {'item_tenue', 'prop_ld_tshirt_01'},
    {'item_tshirt', 'prop_ld_tshirt_01'},
    {'item_gant', 'prop_ld_tshirt_01'},
    {'item_haut', 'prop_ld_tshirt_01'},
    {'item_chaussures', 'prop_ld_shoe_01'},
    {'item_lunettes', 'prop_cs_sol_glasses'},
    -- {'item_kevlar', 'prop_bodyarmour_03'},
    {'item_masque', 'p_trev_ski_mask_s'},
}