allIpls = {
	-- 			WEED LAB

	{
		interiorsProps = {
			"weed_drying",
			"weed_production",
			-- --"weed_set_up",
			-- --"weed_standard_equip",
			"weed_upgrade_equip",
			-- --"weed_growtha_stage1",
			-- --"weed_growtha_stage2",
			--+"weed_growtha_stage3",
			-- --"weed_growthb_stage1",
			-- --"weed_growthb_stage2",
			-- --"weed_growthb_stage3",
			--+"weed_growthc_stage1",
			-- --"weed_growthc_stage2",
			-- --"weed_growthc_stage3",
			--+"weed_growthd_stage1",
			-- --"weed_growthd_stage2",
			-- --"weed_growthd_stage3",
			-- --"weed_growthe_stage1",
			--+"weed_growthe_stage2",
			-- --"weed_growthe_stage3",
			-- --"weed_growthf_stage1",
			--+"weed_growthf_stage2",
			-- --"weed_growthf_stage3",
			--+"weed_growthg_stage1",
			-- --"weed_growthg_stage2",
			-- --"weed_growthg_stage3",
			-- --"weed_growthh_stage1",
			-- --"weed_growthh_stage2",
			--+"weed_growthh_stage3",
			-- --"weed_growthi_stage1",
			--+"weed_growthi_stage2",
			-- --"weed_growthi_stage3",
			--+"weed_hosea",
			--+"weed_hoseb",
			--+"weed_hosec",
			--+"weed_hosed",
			--+"weed_hosee",
			--+"weed_hosef",
			--+"weed_hoseg",
			--+"weed_hoseh",
			--+"weed_hosei",
			-- --"light_growtha_stage23_standard",
			-- --"light_growthb_stage23_standard",
			-- --"light_growthc_stage23_standard",
			-- --"light_growthd_stage23_standard",
			-- --"light_growthe_stage23_standard",
			-- --"light_growthf_stage23_standard",
			-- --"light_growthg_stage23_standard",
			-- --"light_growthh_stage23_standard",
			-- --"light_growthi_stage23_standard",
			--+"light_growtha_stage23_upgrade",
			--+"light_growthb_stage23_upgrade",
			--+"light_growthc_stage23_upgrade",
			--+"light_growthc_stage23_upgrade",
			--+"light_growthd_stage23_upgrade",
			--+"light_growthe_stage23_upgrade",
			--+"light_growthf_stage23_upgrade",
			--+"light_growthg_stage23_upgrade",
			--+"light_growthh_stage23_upgrade",
			--+"light_growthi_stage23_upgrade",
			-- --"weed_low_security",
			"weed_security_upgrade",
			"weed_chairs"
		},
		coords={{1051.491, -3196.536, -39.14842}}
	},

	-- 			FIB Lobby

	{
		interiorsProps = {
			"V_FIB03_door_light",
			"V_FIB02_set_AH3b",
			"V_FIB03_set_AH3b",
			"V_FIB04_set_AH3b"
		},
		coords={{110.4, -744.2, 45.7496}}
	},

	-- 			CLUBHOUSE 1 

	{
		interiorsProps = {
			--"cash_stash1",
			--"cash_stash2",
			"cash_stash3",
			--"coke_stash1",
			--"coke_stash2",
			"coke_stash3",
			--"counterfeit_stash1",
			--"counterfeit_stash2",
			"counterfeit_stash3",
			--"weed_stash1",
			--"weed_stash2",
			"weed_stash3",
			--"id_stash1",
			--"id_stash2",
			"id_stash3",
			--"meth_stash1",
			--"meth_stash2",
			"meth_stash3",
			--"decorative_01",
			--"decorative_02",
			--"furnishings_01",
			--"furnishings_02",
			--"walls_01",
			"walls_02",
			--"mural_01",
			--"mural_02",
			--"mural_03",
			--"mural_04",
			--"mural_05",
			--"mural_06",
			--"mural_07",
			--"mural_08",
			--"mural_09",
			"gun_locker",
			"mod_booth",
			--"no_gun_locker",
			--"no_mod_booth"
		},
		coords={{1107.04, -3157.399, -37.51859}}
	}
}